apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: blog
build:
  artifacts:
  - image: docker.io/boton318/client
    context: client
    docker:
      dockerfile: Dockerfile
  - image: docker.io/boton318/comments
    context: comments
    docker:
      dockerfile: Dockerfile
  - image: docker.io/boton318/event-bus
    context: event-bus
    docker:
      dockerfile: Dockerfile
  - image: docker.io/boton318/moderation
    context: moderation
    docker:
      dockerfile: Dockerfile
  - image: docker.io/boton318/posts
    context: posts
    docker:
      dockerfile: Dockerfile
  - image: docker.io/boton318/query
    context: query
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - infra/k8s/client-depl.yaml
    - infra/k8s/comments-depl.yaml
    - infra/k8s/event-bus-depl.yaml
    - infra/k8s/ingress-srv.yaml
    - infra/k8s/moderation-depl.yaml
    - infra/k8s/posts-depl.yaml
    - infra/k8s/query-depl.yaml
